### PR TITLE
since-3.11: Test except* instead, so comment shows up in 3.10 traceback

### PR DESCRIPTION
**Pull request by andersk**

### CODE REVIEW

**Comment by andersk** [comment]
Huh, this fixes the 3.10 traceback but breaks the 3.1 traceback.

**Comment by andersk** [comment]
I guess we can combine tests. This works now.

**Comment by jwilk** [comment]
Yay, thanks for the PR!

To clarify, the comment did show up when you ran `python3.10 since-3.11.py` by hand, but not when our test suite `exec()`ed the same code. (This smells like a bug in the interpreter, but I don't have time to investigate this further.)
I've fixed the test suite in 2f462934579aab47cfba991b28faa17d47a37870 by running `compile()` first.

But your new code is much better anyway. I'd love to merge it.
Can you rebase on top of master and adjust the commit message?

**Comment by andersk** [comment]
Sure, adjusted.

**Pull request merged**
